version: '3'

services:
    postgres:
        image: postgres
        container_name: finance-app-postgres
        environment:
            POSTGRES_PASSWORD: hardcore8*
            POSTGRES_DB: appfinance
        ports:
            - '5432:5432'
        volumes:
            - postgres_data:/var/lib/postgresql/data

    postgres-test:
        image: postgres
        container_name: finance-app-postgres-test
        environment:
            POSTGRES_PASSWORD: hardcore8*
            POSTGRES_DB: appfinance
        ports:
            - '5433:5432'

    pgadmin:
        image: dpage/pgadmin4
        container_name: finance-app-pgadmin
        environment:
            PGADMIN_DEFAULT_EMAIL: mendes_j27@hotmail.com
            PGADMIN_DEFAULT_PASSWORD: hardcore8*
        ports:
            - '5050:80'
        volumes:
            - pgadmin_data:/var/lib/pgadmin4
        depends_on:
            - postgres

volumes:
    postgres_data:
    pgadmin_data:
